# Service configuration for user-service
service: user-service
frameworkVersion: "3"

# AWS provider settings
provider:
  name: aws
  runtime: nodejs16.x
  versionFunctions: false
  stage: "dev"
  region: eu-central-1
  httpApi:
    cors: true # Enable CORS for HTTP API

# Function definitions
functions:
  # Signup function
  signup:
    handler: app/handler.Signup
    events:
      - httpApi:
          path: /signup
          method: post

  # Login function
  login:
    handler: app/handler.Login
    events:
      - httpApi:
          path: /login
          method: post

  # Verify function
  verify:
    handler: app/handler.Verify
    events:
      - httpApi:
          path: /verify
          method: get
      - httpApi:
          path: /verify
          method: post

  # Profile functions
  profile:
    handler: app/handler.Profile
    events:
      - httpApi:
          path: /user
          method: post
      - httpApi:
          path: /user
          method: put
      - httpApi:
          path: /user
          method: get

  # Cart functions
  cart:
    handler: app/handler.Cart
    events:
      - httpApi:
          path: /cart
          method: post
      - httpApi:
          path: /cart
          method: put
      - httpApi:
          path: /cart
          method: get

  # Payment functions
  payment:
    handler: app/handler.Payment
    events:
      - httpApi:
          path: /payment
          method: post
      - httpApi:
          path: /payment
          method: put
      - httpApi:
          path: /payment
          method: get

# Serverless plugins used
plugins:
  - serverless-offline # Simulate AWS Lambda and API Gateway locally
  - serverless-plugin-typescript # Enable TypeScript support
  - serverless-dotenv-plugin # Loads environment variables from a .env file
